apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petlinic
          image: yulei058/spring-petclinic:1.0.0.RELEASE